run:
  name: humanpair
  job: train
  datasets:
    - human_pair

dataloader:
  batch_size: 6144
  workers: 6
  sampler: default

model_denoising:
  name: transformer_unidiffuser_3
  dim_timestep_embed: 128
  params:
    dim_hidden: 312
    num_layers: 8
    dim_feedforward: 2048
    nhead: 8

model_conditioning:
  use_class_conditioning: false
  use_pointnext_conditioning: false
  use_contacts: NONE
  contact_model: null

model:
  # sbj: 300 betas + 3 global(6D->3?) + 153 pose(6D?) + 3 transl = 459
  data_sbj_channels: 459
  # obj (h2): same as sbj = 459
  data_obj_channels: 459
  # no contact maps
  data_contact_channels: 0
  denoise_mode: sample
  beta_start: 1.0e-05
  beta_end: 0.008
  beta_schedule: linear

train:
  max_steps: 50000
  log_step_freq: 20
  checkpoint_freq: 2500
  print_step_freq: 50
  mirror_shape_weight: 0.8
  losses:
    denoise_1: 1.0
    denoise_2: 1.0

optimizer:
  type: torch
  name: AdamW
  lr: 1e-4
  weight_decay: 1.0e-06
  kwargs:
    betas: [0.95, 0.999]
